[[CURRENCIES]]
code = "LOTG49"
issuer = "GAOI54SELTEVNL6APGH7ZILQHASUQDYD4NOCARUDYFAJ54SQ3NOVRHR"
name = "LOT G49"
desc = "เหรียญทองดิจิทัล Supply 48 ล้าน ไม่ Mint เพิ่ม"
image = "https://raw.githubusercontent.com/nopphaklao7108-alt/golden49-app/main/logo-lotg49.png"
